module Proxy.Types.TechTypes where
-- | The datatype containing all units special abilites
data TechType = Stimpacks
              | Lockdown
              | EMPShockwave
              | SpiderMines
              | ScannerSweep
              | TankSiegeMode
              | DefensiveMatrix
              | Irradiate
              | YamatoGun
              | CloakingField
              | PersonnelCloaking
              | Burrowing
              | Infestation
              | SpawnBroodlings
              | DarkSwarm
              | Plague
              | Consume
              | Ensnare
              | Parasite
              | PsionicStorm
              | Hallucination
              | Recall
              | StasisField
              | ArchonWarp
              | Restoration
              | DisruptionWeb
              | UnusedTech26
              | MindControl
              | DarkArchonMeld
              | Feedback
              | OpticalFlare
              | Maelstorm
              | LurkerAspect
              | UnusedTech33
              | Healing
              | UnusedTech35
              | UnusedTech36
              | UnusedTech37
              | UnusedTech38
              | UnusedTech39
              | UnusedTech40
              | UnusedTech41
              | UnusedTech42
              | UnusedTech43
              | NoneTechType
              | UnknownTechType
              | NuclearStrike deriving (Enum, Show)
