module Proxy.Types.UnitTypes where
-- ^ This module contains the unit types for all species as a datatype.

data UnitType = TerranMarine
              | TerranGhost
              | TerranVulture
              | TerranGoliath
              | TerranGoliathTurret
              | TerranSiegeTankTankMode
              | TerranTankTurretTankMode
              | TerranSCV
              | TerranWraith
              | TerranScienceVessel
              | TerranHeroGuiMontag
              | TerranDropship
              | TerranBattlecruiser
              | TerranVultureSpiderMine
              | TerranNuclearMissile
              | TerranHeroCivilian
              | TerranHeroSarahKerrigan
              | TerranHeroAlanSchezar
              | TerranHeroAlanTurret
              | TerranHeroJimRaynorV
              | TerranHeroJimRaynorM
              | TerranHeroTomKazansky
              | TerranHeroMagellan
              | TerranHeroEdmundDukeT
              | TerranHeroEdmundDukeTTurret
              | TerranHeroEdmundDukeS
              | TerranHeroEdmundDukeSTurret
              | TerranHeroArcturusMengsk
              | TerranHeroHyperion
              | TerranHeroNoradII
              | TerranSiegeTankSiegeMode
              | TerranSiegeTankSiegeTurret
              | TerranFirebat
              | SpellScannerSweep
              | TerranMedic
              | ZergLarva
              | ZergEgg
              | ZergZergling
              | ZergHydralisk
              | ZergUltralisk
              | ZergBroodling
              | ZergDrone
              | ZergOverlord
              | ZergMutalisk
              | ZergGuardian
              | ZergQueen
              | ZergDefiler
              | ZergScourge
              | ZergHeroTorrasque
              | ZergHeroMatriarch
              | ZergInfestedTerran
              | ZergHeroInfestedKerrigan
              | ZergHeroUncleanOne
              | ZergHeroHunterKiller
              | ZergHeroDevouringOne
              | ZergHeroKukulzaMutalisk
              | ZergHeroKukulzaGuardian
              | ZergHeroYggdrasill
              | TerranValkyrie
              | ZergCocoon
              | ProtossCorsair
              | ProtossDarkTemplar
              | ZergDevourer
              | ProtossDarkArchon
              | ProtossProbe
              | ProtossZealot
              | ProtossDragoon
              | ProtossHighTemplar
              | ProtossArchon
              | ProtossShuttle
              | ProtossScout
              | ProtossArbiter
              | ProtossCarrier
              | ProtossInterceptor
              | ProtossHeroDarkTemplar
              | ProtossHeroZeratul
              | ProtossHeroTassadarZeratul
              | ProtossHeroFenixZealot
              | ProtossHeroFenixDragoon
              | ProtossHeroTassadar
              | ProtossHeroMojo
              | ProtossHeroWarbringer
              | ProtossHeroGantrithor
              | ProtossReaver
              | ProtossObserver
              | ProtossScarab
              | ProtossHeroDanimoth
              | ProtossHeroAldaris
              | ProtossHeroArtanis
              | CritterRhynadon
              | CritterBengalaas
              | UnusedCargoShip
              | UnusedMercenaryGunship
              | CritterScantid
              | CritterKakaru
              | CritterRagnasaur
              | CritterUrsadon
              | ZergLurkerEgg
              | ProtossHeroRaszagal
              | TerranHeroSamirDuran
              | TerranHeroAlexeiStukov
              | MapRevealer
              | TerranHeroGerardDuGalle
              | ZergLurker
              | ZergHeroInfestedDuran
              | SpellDisruptionWeb
              | TerranCommandCenter
              | TerranComsatStation
              | TerranNuclearSilo
              | TerranSupplyDepot
              | TerranRefinery
              | TerranBarracks
              | TerranAcademy
              | TerranFactory
              | TerranStarport
              | TerranControlTower
              | TerranScienceFacility
              | TerranCovertOps
              | TerranPhysicsLab
              | UnusedStarbase
              | TerranMachineShop
              | UnusedRepairBay
              | TerranEngineeringBay
              | TerranArmory
              | TerranMissileTurret
              | TerranBunker
              | SpecialCrashedNoradII
              | SpecialIonCannon
              | PowerupUrajCrystal
              | PowerupKhalisCrystal
              | ZergInfestedCommandCenter
              | ZergHatchery
              | ZergLair
              | ZergHive
              | ZergNydusCanal
              | ZergHydraliskDen
              | ZergDefilerMound
              | ZergGreaterSpire
              | ZergQueensNest
              | ZergEvolutionChamber
              | ZergUltraliskCavern
              | ZergSpire
              | ZergSpawningPool
              | ZergCreepColony
              | ZergSporeColony
              | UnusedZergBuilding1
              | ZergSunkenColony
              | SpecialOvermindWithShell
              | SpecialOvermind
              | ZergExtractor
              | SpecialMatureChrysalis
              | SpecialCerebrate
              | SpecialCerebrateDaggoth
              | UnusedZergBuilding2
              | ProtossNexus
              | ProtossRoboticsFacility
              | ProtossPylon
              | ProtossAssimilator
              | UnusedProtossBuilding1
              | ProtossObservatory
              | ProtossGateway
              | UnusedProtossBuilding2
              | ProtossPhotonCannon
              | ProtossCitadelOfAdun
              | ProtossCyberneticsCore
              | ProtossTemplarArchives
              | ProtossForge
              | ProtossStargate
              | SpecialStasisCellPrison
              | ProtossFleetBeacon
              | ProtossArbiterTribunal
              | ProtossRoboticsSupportBay
              | ProtossShieldBattery
              | SpecialKhaydarinCrystalForm
              | SpecialProtossTemple
              | SpecialXelNagaTemple
              | ResourceMineralPatch1
              | ResourceMineralPatch2
              | ResourceMineralPatch3
              | UnusedCave
              | UnusedCaveIn
              | UnusedCantina
              | UnusedMiningPlatform
              | UnusedIndependantCC
              | UnusedIndependantStarport
              | UnusedIndependantJumpGate
              | UnusedRuins
              | UnusedKhaydarinFormation
              | ResourceVespeneGeyser
              | SpecialWarpGate
              | SpecialPsiDisrupter
              | UnusedZergMarker
              | UnusedTerranMarker
              | UnusedProtossMarker
              | BeaconZerg
              | BeaconTerran
              | BeaconProtoss
              | BeaconZergFlag
              | BeaconTerranFlag
              | BeaconProtossFlag
              | SpecialPowerGenerator
              | SpecialOvermindCocoon
              | SpellDarkSwarm
              | DoodadFloorMissileTrap
              | DoodadFloorHatch
              | DoodadLeftUpperLevelDoor
              | DoodadRightUpperLevelDoor
              | DoodadLeftPitDoor
              | DoodadRightPitDoor
              | DoodadFloorGunTrap
              | DoodadLeftWallMissileTrap
              | DoodadLeftWallFlameTrap
              | DoodadRightWallMissileTrap
              | DoodadRightWallFlameTrap
              | StartLocation
              | PowerupFlag
              | PowerupYoungChrysalis
              | PowerupPsiEmitter
              | PowerupDataDisk
              | PowerupKhaydarinCrystal
              | MineralChunk1
              | MineralChunk2
              | VespeneOrb1
              | VespeneOrb2
              | VaspeneSac1
              | VaspeneSac2
              | VespeneTank1
              | VespeneTank2
              | NoneUnitType
              | UnknownUnitType deriving (Enum, Show, Eq)
